name: OnlyPlayWithStreamers
author: remadisson
version: 1.0.0
api-version: 1.16
description: This Plugin disallows 'normal' Players to grief or to do other stupid stuff. They get kicked when a Streamer lefts.
website: https://www.remadyreturns.de/

main: de.remadisson.opws.main

commands:
  streamer:
    description: Allows to add Streamers to the List, so they can join.
  worker:
    description: Allows to add other Allowed Players, so they can join idependently.
  whitelist:
    description: Replaces the default Whitelist-Command.
    aliases: ['wl']
  warp:
    description: Allows players to teleport to certain positions in different worlds.
    aliases: ['warps']
  gamemode:
    description: Changes your gamemode, bitch!
    aliases: ['gm']
  city:
    description: Allows Streamers to add own cities.
  setup:
    description: Set some fudamental Variables for the maintenance part of the Event.
  arena:
    description: Completes the functionality for the Arena.
  staff:
    description: Gives you opportunities!
  kick:
    description: Kicks Players for you!
  banlist:
    description: Lists the bans.
  ban:
    description: This is probably a description for an obvious.
  unban:
    description: This is probably a description for an obvious command.