name: OnlyPlayWithStreamers
author: remadisson
version: 1.0.0
website: https://www.remadyreturns.de/

main: de.remadisson.opws.main

commands:
  streamer:
    description: Allows to add Streamers to the List, so they can join.
  allowed:
    description: Allows to add other Allowed Players, so they can join idependently.
  whitelist:
    description: Replaces the default Whitelist-Command.