name: OnlyPlayWithStreamers
author: remadisson
version: 1.0.0
api-version: 1.16
description: This Plugin disallows 'normal' Players to grief or to do other stupid stuff. They get kicked when a Streamer lefts.
website: https://www.remadyreturns.de/

main: de.remadisson.opws.main

commands:
  streamer:
    description: Allows to add Streamers to the List, so they can join.
  allowed:
    description: Allows to add other Allowed Players, so they can join idependently.
  whitelist:
    description: Replaces the default Whitelist-Command.
    aliases: ['wl']
  warp:
    description: Allows players to teleport to certain positions in different worlds.
    aliases: ['warps']
  gamemode:
    description: Changes your gamemode, bitch!
    aliases: ['gm']